### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by jpmeijers** [disk91/helium-gateway-rs-docker#3]
This repo and guide works well. I would however prefer to use Docker Compose to manage the containers, and not a custom run script along with raw docker commands. I believe it should be simple to move the configurations into volume mounts and environment variables, and then have a docker-compose.yml file with entries for each gateway.

If I get a chance I will try to do it and file a PR.

**Comment by jpmeijers** [comment]
Some progress in this regard. The docker-compose.yaml file below can be used to run multiple instances of the gateway-rs image. 

Explanation:
* `eui-0123456789abcdef` is the container's name. I used the gateway's eui for this for clarity.
* Under `ports` the port to the outside world comes first, and maps to 1680 inside the container. The first number therefore needs to be unique per gateway, while the second one should always be 1680.
* Under `volumes` we mount a directory on the host server into the container. We put the `gateway_key.bin` in this directory.
* The normal settings can be change in the environment part according to https://github.com/helium/gateway-rs#envrionment-variables

Usage:
* Create a directory on the server and put this content below in a `docker-compose.yml` file in this directory.
* Create a subdirectory for each gateway.
* If you have existing `gateway_key.bin` files, copy each gateway's one into its respective directory. If you are setting up a new gateway, leave the directory blank. gateway-rs will create a new `gateway_key.bin` inside this directory at startup. After the first start, make a backup of this `gateway_key.bin`.
* For each gateway create a block like below. Below we have two examples, one for `eui-0123456789abcdef` and one for `test`.
* Update the port and the volume values. Port should be unique per gateway, volume should be the directory for the respective gateway. 

To run all the containers, execute: `docker-compose up -d`
To stop all the containers: `docker-compose down`
To see the logs of a specific container: `docker-compose logs -f --tail=1000 eui-0123456789abcdef`
To update the containers to the latest gateway-rs: `docker-compose up -d --build`

```
version: "3"

services:

  eui-0123456789abcdef:
    build:
      context: https://github.com/helium/gateway-rs.git#main
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1680:1680/udp"
    volumes:
      - ./eui-0123456789abcdef:/opt/helium_gateway
    environment:
      - GW_KEYPAIR=/opt/helium_gateway/gateway_key.bin
      - GW_REGION=EU868
      - GW_LOG_LEVEL=debug
      - GW_LOG_TIMESTAMP=true
      - GW_UPDATE_ENABLED=false

  test:
    build:
      context: https://github.com/helium/gateway-rs.git#main
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1702:1680/udp"
    volumes:
      - ./test:/opt/helium_gateway
    environment:
      - GW_KEYPAIR=/opt/helium_gateway/gateway_key.bin
      - GW_REGION=EU868
      - GW_LOG_LEVEL=debug
      - GW_LOG_TIMESTAMP=true
      - GW_UPDATE_ENABLED=false
```
